version: "3.8"
services:
  pclinic-server:
    container_name: pclinicapp
    build:
        context: .
    ports:
      - 8888:8080
      - 8000:8000
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinicdb
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    depends_on:
      - mysqlserver
  mysqlserver:
    image: mysql:latest
    ports:
      - 3316:3306
    environment:
      - MYSQL_ROOT_PASSWORD=topsecret
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=pclinic
      - MYSQL_DATABASE=petclinicdb
    volumes:
      - /Users/vanilla/Projects/practise/docker/jdocker/mysqldata/data:/var/lib/mysql
      - /Users/vanilla/Projects/practise/docker/jdocker/mysqldata/config:/etc/mysql/conf.d

